name: Static Analysis

on: [push, pull_request]

jobs:
  inspect-code:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        run: pip install flake8
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero shows all errors but does not fail.
          flake8 . --count --exit-zero --max-line-length=80 --ignore=E111,E121,E126 --statistics
  