name: No Duplications

on: [push, pull_request]

jobs:
  nodups:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install jscpd
      run: sudo npm install -g jscpd

    - name: No Duplication beyond 3 lines
      run:  jscpd *.py --gitignore --min-lines 3 --min-tokens 25 --threshold 0
